thhb/core/urls.py
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('under_construction/', views.no_access_view, name='under_construction'),
    path('post_list', views.post_list, name='post_list'),
    path('create_post', views.create_blogpost, name='create_post'),
    path('userpage', views.userpage, name='user_page'),
    path('update_post/<slug:post_slug>/', views.update_blogpost, name='update_post'),
    path('<slug:post_slug>/', views.show_single_post, name='single_post'),
]

thhb/thhb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from core.views import home

import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'accounts/password_change/',
        auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change',
    ),
    path(
        'accounts/password_change/done/',
        auth_views.PasswordChangeView.as_view(template_name='password_change_done.html'),
        name='password_change_done',
    ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
]


if settings.DEBUG:
    urlpatterns += static('/static/',
                          document_root=os.path.join(settings.BASE_DIR, 'static/'))

thhb/core/models.py
from django.db import models
from django.template.defaultfilters import slugify

from tinymce.models import HTMLField
import datetime


class BlogPost(models.Model):

    class CategoryType(models.TextChoices):
        MAIN = 'MN', 'Main'
        RELATED = 'RL', 'Related'
        OTHER = 'OT', 'Other'

    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, null=False, unique=True)
    subtitle = models.CharField(max_length=250)
    author = models.CharField(max_length=50, default="Nicholas Thorne")
    image = models.ImageField(upload_to='static/img/', null=False, blank=False)
    image_alt = models.CharField(max_length=100)
    pub_date = models.DateField(default=datetime.date.today)
    last_updated = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=2,
                                choices=CategoryType.choices,
                                default=CategoryType.MAIN)

    content = HTMLField()

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:single_post", kwargs={"slug": self.slug})

    # Auto-generate slug from title when saving
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

thhb/core/forms.py
from django import forms
from .models import BlogPost


class BlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('title', 'subtitle', 'author', 'pub_date', 'category', 'image', 'image_alt', 'content')
        prepopulated_fields = {'slug': ('title',)}
      #  exclude = ['published_date']

thhb/core/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import BlogPostForm
from .models import BlogPost
from django.shortcuts import redirect

import os


@login_required(login_url='/under_construction/')
def home(request):
    post = BlogPost.objects.latest('pub_date')
    return render(request, 'index.html', {'post': post})


@login_required(login_url='/under_construction/')
def book(request):
    return render(request, 'thebook.html')


def no_access_view(request):
    return render(request, 'under_construction.html')


@login_required(login_url='/under_construction/')
def userpage(request):
    return render(request, 'userpage.html')


def get_word_count(str_var):
    """
    The blog posts, entered via TinyMCE, have HTML in them. To get a more accurate word count,
    we first remove much of the HTML (etc.) that commonly comes from a rich text editor.
    """
    ret_str = str_var.replace("<p class='parag'>", "") \
                     .replace("</p>", "") \
                     .replace("<em>", "") \
                     .replace("</em>", "") \
                     .replace("\n", "") \
                     .replace("&ndash;", "") \
                     .replace("&rsquo;", "") \
                     .replace("&lsquo;", "") \
                     .replace("&ldquo;", "") \
                     .replace("&rdquo;", "") \
                     .replace("<a href=", "") \
                     .replace("<span style=", "")

    return len(ret_str.split())


@login_required(login_url='/under_construction/')
def show_single_post(request, post_slug):
    blog_post = BlogPost.objects.get(slug=post_slug)
    if post_slug == 'the-book':
        """
        # Because the template thebook.html is laid out a bit differently than other
        # posts, the content is split into two paragraphs that go before the
        # picture, and those that come after it
        """
        chunks = blog_post.content.replace('\n', '').split('</p>')
        first_paragraphs, last_paragraphs = '</p>'.join(chunks[:2]) + '</p>', '</p>'.join(chunks[2:])
        return render(request, 'thebook.html', {'blog_post': blog_post,
                                                'first_paragraphs': first_paragraphs,
                                                'last_paragraphs': last_paragraphs})

    word_count = get_word_count(blog_post.content)
    return render(request, 'single_post.html', { 'blog_post': blog_post, 'word_count': word_count })


@login_required(login_url='/under_construction/')
def post_list(request):
    posts = BlogPost.objects.filter(category='MN')
    return render(request, 'post_list.html', {'posts': posts})


def adjust_content(content):
    """
    The TinyMCE text editor returns its own HTML, which needs to be adjusted a bit to remove
    superfluous material and add the appropriate class to paragraphs...
    """
    new_content = content.replace('<p>&nbsp;</p>', '') \
                     .replace('\r', '') \
                     .replace('<p>', "<p class='parag'>") \
                     .replace('<p lang="en-GB">', "<p class='parag'>") \
                     .replace('<p lang="en-CA">', "<p class='parag'>") \
                     .replace('<p lang="en-US">', "<p class='parag'>") \
                     .replace('<span lang="en-GB">', '') \
                     .replace('<span lang="en-CA">', '') \
                     .replace('<span lang="en-US">', '') \
                     .replace('</span>', '')
#                     .replace('<a', '<a target="_blank" rel="noopener noreferrer"')

    return new_content


@login_required(login_url='/under_construction/')
def create_blogpost(request):
    if request.user.write_access:
        if request.method == 'POST':
            form = BlogPostForm(request.POST, request.FILES)
            if form.is_valid():
                new_post = form.save(commit=False)
                new_post.content = adjust_content(new_post.content)
                new_post.save()
                return redirect(f'/{new_post.slug}/')
            else:
                print("Form not valid. Errors: {form.errors}")
        else:
            form = BlogPostForm()

        return render(request, 'blogpost.html', { 'form':form })
    else:
        return render(request, 'insufficient_privileges.html')


@login_required(login_url='/under_construction/')
def update_blogpost(request, post_slug):
    blog_post = get_object_or_404(BlogPost, slug = post_slug)
    form = BlogPostForm(request.POST or None, request.FILES or None, instance = blog_post)

    if request.user.write_access:
        if request.method == 'POST':
            old_version = BlogPost.objects.get(slug = post_slug)
            if form.is_valid():
                # The old version of the image must be deleted
                image_path = old_version.image.url
                if image_path[0] == '/': # If the path starts out with '/static', it doesn't get found
                    image_path = image_path[1:]
                if os.path.exists(image_path):
                    os.remove(image_path)

                updated_post = form.save(commit=False)
                updated_post.content = adjust_content(updated_post.content)
                updated_post.save()
                return redirect(f'/{updated_post.slug}/')
        else:
            context = {'form': form}
            return render(request, 'blogpost.html', context)
    else:
        return render(request, 'insufficient_privileges.html')

thhb/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Spectral"
    />
    <link rel="stylesheet" href="{% static 'thhb.css' %}" />
    <title>This Has Happened Before</title>
    <link rel="icon" type="image/ico" href="{% static 'ColumnDrawing.ICO' %}" />
  </head>
  <body>
  {% if user.is_authenticated %}
    <div class="usernav">
      <a href="{% url 'core:user_page' %}" class="usernav__username">{{ user.username }}</a>
      <a href="{% url 'logout' %}" class="usernav__logout">Logout</a>
    </div>
  {% endif %}
    <div class="whole-page">
      <div class="header">
        <div class="header__main">
          <div class="header__title">
            <a href="{% url 'core:home' %}" class="header__title">This Has Happened Before</a>
          </div>
          <div class="header__subtitle">
            Ancient Athens' Cultural Crisis and Our Own
          </div>
        </div>
        <div class="subheader">
          <div class="subheader__content">
            <a href="{% url 'core:single_post' 'introduction' %}" class="subheader__item">Introduction</a>
            <a href="{% url 'core:single_post' 'the-book' %}" class="subheader__item">The Book</a>
            <a href="{% url 'core:post_list' %}" class="subheader__item">Posts</a>
            <a href="#" class="subheader__item">Related Writing</a>
          </div>
        </div>
      </div>
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

thhb/core/templates/blogpost.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        {{form.media}}

        <input class="btn" type="submit" value="Submit">
    </form>
{% endblock %}

thhb/core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div class="landing_page" style="background-image: url({% static 'parthenon_temple.jpg' %});">
        <div class="landing_page__teaser">
          <div class="landing_page__teaser__width-set">
            <div class="landing_page__teaser__width-set__titles">
              <p class="landing_page__teaser__width-set__titles__head">
                In the late 5<span class="superscript">th</span> century BC,
                Plato and Thucydides found their culture in crisis, forcing individuals to work out for themselves many things that had long been taken for granted.
              </p>
              <p class="landing_page__teaser__width-set__titles__sub">
                This blog examines how these two ancient Greeks thought about their time, and how
                they can help us to see more deeply into our own.
              </p>
            </div>
          </div>
        </div>
        <div class="landing_page__new-here">
          <div class="landing_page__new-here__width-set">
            <p class="landing_page__new-here__title">New Here?</p>
            <p class="landing_page__new-here__text">
              <a href="{% url 'core:single_post' 'introduction' %}" class="landing_page__new-here__link">This</a> is the
              first post. It's a good place to start.
            </p>
          </div>
        </div>
        <div class="landing_page__posts">
          <div class="landing_page__posts__width-set">
            <p class="landing_page__posts__title">Latest Post</p>
            <div class="landing_page__posts__card">
              <a href="{% url 'core:single_post' post.slug %}" class="landing_page__posts__card__title">
                {{ post.title }}
              </a>
              <div class="landing_page__posts__card__text">
                {{ post.content|cut:"<p class='parag'>"|truncatewords:35 }}
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

thhb/core/templates/insufficient_privileges.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="insufficient">
    Sorry, but user <em style="text-transform: uppercase;">{{ user.username }}</em> does not have sufficient privileges to access this page.
  </div>
{% endblock %}

thhb/core/templates/password_change.html
{% extends 'base.html' %}

{% block title %}Enter new password{% endblock %}

{% block content %}

{% if user.is_authenticated %}

  {% if user.username != 'guest' %}

    <div class="login-text">
        <h1 class="user-title">User <span class="user-title__name">{{ user.username }}</span></h1>
        <h1>Set a new password</h1>
        <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Change my password">
        </form>
        <p>Click <a href="{% url 'core:user_page' %}">here</a>  to return to the user page.</p>
    </div>
  {% else %}

    <div class="main-text">
        <p>User GUEST cannot perform a password change.</p>
        <p>Click <a href="{% url 'core:user_page' %}">here</a>  to return to the user page.</p>
    </div>
  {% endif %}

{% else %}

<div class="main-text">
    <p>Please log in before visiting this page.</p>
</div>

{% endif %}
{% endblock %}

thhb/core/templates/password_change_done.html
{% extends 'base.html' %}

{% block title %}Successful PW Change{% endblock %}

{% block content %}

{% if user.is_authenticated %}

  <div class="login-text">
      <h1 class="user-title">User <span class="user-title__name">{{ user.username }}</span></h1>
      <h1>Password reset complete</h1>
      <p>Your new password has been set. Click <a href="{% url 'core:user_page' %}">here</a> to return to the user page.</p>
  </div>

{% else %}

  <div class="main-text">
      <p>Please log in before visiting this page.</p>
  </div>

{% endif %}
{% endblock %}

thhb/core/templates/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

      <div class="blogpost-list-container">
        <div class="blogposts-title">List of Posts</div>
        <div class="card-container">
        {% for post in posts %}
          <div class="blogpost-card">
            <a href="{% url 'core:single_post' post.slug %}" class="blogpost-card__title">
              {{ post.title }}
            </a>
            <div class="blogpost-card__date">{{ post.pub_date|date:"F d, Y" }}</div>
            <img
              src="{{ post.image.url }}"
              alt="{{ post.image_alt }}"
              class="blogpost-card__image"
            />
            <div class="blogpost-card__opening-words">
              {{ post.content|cut:"<p class='parag'>"|truncatewords:20 }}
            </div>
          </div>
        {% endfor %}
          </div>
       </div>
{% endblock %}

thhb/core/templates/single_post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div class="main">
        <div class="article-top">
          {% if user.is_authenticated and user.write_access %}
            <a href="{% url 'core:update_post' blog_post.slug %}" class="article-top__btn btn">Edit Post</a>
          {% endif %}
          <div class="article-top__title">
            {{ blog_post.title }}
            <div class="article-top__subtitle">
              {{ blog_post.subtitle }}
            </div>
          </div>
          <div class="article-top__pubinfo">
            <div class="article-top__pubinfo__name">{{ blog_post.author }}</div>
            <div class="article-top__pubinfo__date">{{ blog_post.pub_date|date:"F d, Y" }}</div>
          </div>
          <img
            src="{{ blog_post.image.url }}"
            alt="{{ blog_post.image_alt }}"
            class="article-top__image"
          />
        </div>
        {{ blog_post.content | safe }}
        <p class="parag word_count">Word Count: {{ word_count }}</p>
      </div>
{% endblock %}

thhb/core/templates/thebook.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div class="main">
        <div class="article-top book_title_top">
          {% if user.is_authenticated and user.write_access %}
            <a href="{% url 'core:update_post' blog_post.slug %}" class="article-top__btn btn">Edit Post</a>
          {% endif %}
          <div class="article-top__title">The Book</div>
        </div>
        {{ first_paragraphs | safe }}
        <div class="bookpic_container">
          <img
            src="{{ blog_post.image.url }}"
            alt="{{ blog_post.image_alt }}"
            class="book_image"
          />
        </div>
        {{ last_paragraphs | safe }}
      </div>
{% endblock %}

thhb/core/templates/under_construction.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>This Has Happened Before</title>
  <link rel="icon" type="image/ico" href="{% static 'ColumnDrawing.ICO' %}" />
  <link rel="stylesheet" href="{% static 'temporary_pages.css' %}" />
</head>
<body style="background-image: url({% static 'under_construction.jpeg' %});">
  <div class="container">
    <div class="main-text">
    This site is under construction.</div>
    <div class="main-text"> It is not likely to be open for quite some time yet...
    </div>
    <div class="sub-text">Those authorised to look around within are invited to sign in.</div>
    <a href="{% url 'login' %}" class="login-btn">
      Sign In
    </a>
  </div>
</body>
</html>

thhb/core/templates/userpage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div class="userpage">
        <div class="userpage__title">
          User Page for <em class="userpage__name">{{ user.username }}</em>
        </div>
          <a href="{% url 'logout' %}" class="userpage__btn btn">Logout</a>
        {% if user.write_access %}
          <div href="#" class="userpage__write-access">Write Access</div>
          <a href="{% url 'core:create_post' %}" class="userpage__btn btn">Create New Post</a>
          <a href="{% url 'password_change' %}" class="userpage__btn btn">Change Password</a>
        {% else %}
          <div class="userpage__write-access">No Write Access</div>
          <div class="userpage__write-access">Cannot write or edit posts</div>
          <div class="userpage__write-access">Cannot change password</div>
        {% endif %}
      </div>

{% endblock %}